# Generated by Django 6.0.7 on 2026-07-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Pie de foto')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('suggested_link', models.URLField(blank=True, verbose_name='Enlace de Compra')),
                ('image', models.ImageField(upload_to='gifts/', verbose_name='Imagen')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Stock Ilimitado/Múltiple')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Regalo',
                'verbose_name_plural': 'Regalos',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Teléfono')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('rsvp_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('DECLINED', 'No Asistirá')], default='PENDING', max_length=15, verbose_name='Estado RSVP')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
            },
        ),
        migrations.CreateModel(
            name='GiftReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='invitations.gift', verbose_name='Regalo')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_reservations', to='invitations.guest', verbose_name='Invitado')),
            ],
            options={
                'verbose_name': 'Reserva de Regalo',
                'verbose_name_plural': 'Reservas de Regalos',
                'unique_together': {('gift', 'guest')},
            },
        ),
    ]
