module.exports = {
    darkMode: "class",
    content: [
        '../templates/**/*.html',
        '../../templates/**/*.html',
        '../../**/templates/**/*.html',
        '../../../frontend/templates/**/*.html',
        '../../../frontend/assets/js/**/*.js',
    ],
    theme: {
        extend: {
            "colors": {
                "primary": "#785252",
                "surface-container": "#f2edea",
                "secondary-fixed": "#eee0d5",
                "on-secondary-fixed": "#211a14",
                "surface-container-lowest": "#ffffff",
                "on-secondary-container": "#6b6158",
                "tertiary-fixed-dim": "#bfc9c3",
                "outline-variant": "#d4c2c2",
                "inverse-surface": "#32302e",
                "primary-fixed-dim": "#ebbbba",
                "on-primary": "#ffffff",
                "surface-container-high": "#ece7e4",
                "surface": "#fdf8f5",
                "on-surface": "#1c1b1a",
                "on-tertiary-fixed": "#151d1a",
                "secondary-container": "#ebddd2",
                "inverse-on-surface": "#f5f0ed",
                "on-background": "#1c1b1a",
                "on-secondary": "#ffffff",
                "primary-fixed": "#ffdad9",
                "secondary-fixed-dim": "#d2c4b9",
                "surface-bright": "#fdf8f5",
                "error": "#ba1a1a",
                "surface-container-low": "#f8f3f0",
                "on-error-container": "#93000a",
                "error-container": "#ffdad6",
                "on-surface-variant": "#504444",
                "surface-variant": "#e6e2df",
                "primary-container": "#936a6a",
                "surface-container-highest": "#e6e2df",
                "on-tertiary-container": "#f5fff9",
                "on-error": "#ffffff",
                "on-tertiary": "#ffffff",
                "inverse-primary": "#ebbbba",
                "tertiary-fixed": "#dbe5df",
                "on-primary-container": "#fffbff",
                "surface-tint": "#7a5555",
                "tertiary": "#545e5a",
                "tertiary-container": "#6d7772",
                "surface-dim": "#ded9d6",
                "on-primary-fixed": "#2f1314",
                "outline": "#827473",
                "on-primary-fixed-variant": "#603e3e",
                "secondary": "#675d54",
                "on-secondary-fixed-variant": "#4e453d",
                "on-tertiary-fixed-variant": "#3f4945",
                "background": "#fdf8f5"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-sm": "8px",
                "container-padding": "20px",
                "stack-lg": "32px",
                "stack-md": "16px",
                "gutter": "16px",
                "margin-page": "24px"
            },
            "fontFamily": {
                "body-md": ["Be Vietnam Pro", "sans-serif"],
                "label-md": ["Be Vietnam Pro", "sans-serif"],
                "headline-md": ["Playfair Display", "serif"],
                "body-lg": ["Be Vietnam Pro", "sans-serif"],
                "headline-lg": ["Playfair Display", "serif"],
                "headline-sm": ["Playfair Display", "serif"],
                "headline-lg-mobile": ["Playfair Display", "serif"]
            },
            "fontSize": {
                "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500" }],
                "headline-md": ["28px", { "lineHeight": "1.3", "fontWeight": "500" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "headline-lg": ["36px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "headline-sm": ["22px", { "lineHeight": "1.4", "fontWeight": "500" }],
                "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }]
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
}
